inputDirectory: ../javatots-test
outputDirectory: ../javatots-test/asTypescript
packageTemplate: "// Corresponding javatots-test package: %s"
indentation: 2
unknownImportTemplate: "import { %s } from %s;"
commentThrows: true
unknownAnnotations: comment # comment, ignore, throw (everything else interpreted as throw)

moduleMaps:
  customer-db:
    srcRoot: src/main/java
    outputPath: packages/custdb/src
    packageMaps:
      - pkg: org.javatots.example.customerdb.models
        destPath: records
      - pkg: org.javatots.example.customerdb
        destPath:
  customer-app:
    srcRoot: src/main/java
    outputPath: packages/custapp
    packageMaps:
      - pkg: org.javatots.example.customerapp
        destPath: src
