inputDirectory: ../javatots-test/
outputDirectory: asTypescript

moduleMaps:
  customer-db:
    outputPath: custdb
    srcRoot: src/main/java/
    packageMaps:
      - pkg: org.javatots.example
        destPath:
  customer-app:
    outputPath: custapp
    srcRoot: src/main/java/
    packageMaps:
      - pkg: org.javatots.example
        destPath:
