inputDirectory: ../javatots-test
outputDirectory: asTypescript
packageTemplate: "// Corresponding javatots-test package: %s"
indentation: 2

moduleMaps:
  customer-db:
    srcRoot: src/main/java
    outputPath: packages/custdb
    packageMaps:
      - pkg: org.javatots.example
        destPath: src
  customer-app:
    srcRoot: src/main/java
    outputPath: packages/custapp
    packageMaps:
      - pkg: org.javatots.example
        destPath: src
